name: semgrep-publish

on:
  push:
    branches:
    - develop
    - main
    - master
    paths:
    - .github/workflows/semgrep-publish.yml
jobs:
  publish:
    name: public-private-semgrep-rules
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: publish private semgrep rules
      run: |
        docker run --env SEMGREP_APP_TOKEN=$SEMGREP_APP_TOKEN returntocorp/semgrep:develop semgrep install-semgrep-pro
        docker run --env SEMGREP_APP_TOKEN=$SEMGREP_APP_TOKEN returntocorp/semgrep:develop semgrep --pro --validate --config test.yaml
