on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci --verbose --time --json --output=semgrep-run.json
    - name: upload-artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: semgrep-run.json
        path: semgrep-run.json
        retention-days: 5
  
