on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  buildGradleLockfile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build lockfile
      run: gradle dependencies --write-locks > gradlelockfile.txt
    - name: Upload lockfile Artifact     
      uses: actions/upload-artifact@v3
      with:
        name: gradlelockfile
        path: gradlelockfile.txt
  semgrep:
    needs: buildGradleLockfile
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci --verbose

          
