name: semgrep-publish

on:
  push:
    branches:
    - develop
    - main
    - master
    paths:
    - .github/workflows/semgrep-publish.yml
jobs:
  publish:
    name: public-private-semgrep-rules
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: |
        semgrep --pro --validate --config test.yaml
