on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  buildGradleLockfile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build lockfile
      run: gradle dependencies --write-locks 
    - name: Upload lockfile Artifact     
      uses: actions/upload-artifact@v3
      with:
        name: gradlelockfile
        path: gradle.lockfile
  semgrep:
    needs: buildGradleLockfile
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v3
      - name: Download artifact from previous job
        uses: actions/download-artifact@v3
        with:
          name: gradlelockfile
      - uses: returntocorp/semgrep-action@v1
        with:
          publishToken: ${{ secrets.SEMGREP_APP_TOKEN }}
