on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
  
  tag:
    needs: semgrep
    name: Tag project time
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - run: |
          curl \
          -X PATCH https://semgrep.dev/api/v1/deployments/jason_lim00/projects/${GITHUB_REPOSITORY}
          -H "Authorization: bearer ${{ secrets.SEMGREP_APP_TOKEN }}" \
          -d '{"tags": \["sometaga", "sometagb", "BAPPID-1234"\]}'
