on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  buildGradleLockfile: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Build lockfile
      run: ./gradlew dependencies --write-locks 
    - name: Upload lockfile Artifact     
      uses: actions/upload-artifact@v3
      with:
        name: gradlelockfile
        path: buildscript-gradle.lockfile
  semgrep:
    needs: buildGradleLockfile
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci 

          
