on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci 
    - name: package-logs
      if: always()
      run: tar czf logs.tgz ~/.semgrep/last.log
    - name: upload-logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: logs.tgz
        path: logs.tgz
        retention-days: 5
  

