on:
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
    - uses: actions/checkout@v3
    - run: semgrep ci
    
  publish:
    name: public-private-semgrep-rules
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: semgrep-rules
    - name: publish private semgrep rules
      run: |
        echo "${GITHUB_WORKSPACE}/semgrep-rules:/src"
        echo "Test"
      env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}

  tag:
    needs: semgrep
    name: Tag project
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    steps:
      - run: |
          curl \
          -H "Authorization: bearer ${{ secrets.SEMGREP_APP_TOKEN }}" \
          https://semgrep.dev/api/v1/deployments/jason_lim00/findings?repos="${GITHUB_REPOSITORY}"

  
